name: Tests and Lint PR

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.github/*'
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: read
  pull-requests: write

env:
  DAGGER_VERSION: 0.18.10
  GEMINI_API_KEY: ${{ secrets.LLM_API_KEY }}

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Lint
        uses: dagger/dagger-for-github@8.0.0
        with:
          verb: call
          args: --ref ${{ github.ref }} lint
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: ${{ env.DAGGER_VERSION }}

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Test
        uses: dagger/dagger-for-github@8.0.0
        with:
          verb: call
          args: --ref ${{ github.ref }} test
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: ${{ env.DAGGER_VERSION }}

  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: Setup agent token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run check
        uses: dagger/dagger-for-github@8.0.0
        with:
          verb: call
          args: --ref ${{ github.ref }} check --github-token GH_TOKEN --commit $GITHUB_SHA --model gemini-2.0-flash
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: ${{ env.DAGGER_VERSION }}
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

